### PR TITLE
patch for server.js to allow for resource url transformation.

### PR DESCRIPTION
**Pull request by Woodya**
motivation:
we're running prerender locally; we want to be able to modify the resource urls to localhost based urls that our local caching server will proxy. Additionally, when calling into our app, we can talk directly to the local server rather than re-traversing the network + ELB etc.

additionally, our app dynamically loads content as the js is executed, the current implementation was often rendering before various resources had been loaded by prerender, i noticed this was only for content loaded dynamically, so i added a simple check for pendingRequests that waits for pending requests before responding.

the commit:
- resource-transforms.json contains an array of {"regexp": String, "flags": String, "sub": String}
  - transforms iterated in order, first to change the url will cause requestData.changeUrl() & no
    further checking of the transforms. All transforms are checked *after* the blockedResources.
- also includes a modification to evaluateJavascriptOnPage to wait for pendingRequests to reach 0.
  (they might be initiated after a js execution phase if the page is dynamic)

example config:
[{"regexp": "https?://(.*.cloudfront.net/)", "sub": "http://127.0.0.1:7777/cacher/$1"}]

### CODE REVIEW

**Comment by thoop** [comment]
Thanks for the pull request!

The resource transformations are cool, but I think I'd rather make `onResourceRequested` call a method to allow you to build that as a plugin to use instead of baking it into Prerender.

As for the `req.prerender.pendingRequests` addition, we are assuming that the page is done loading at that point. If it's not, we need to change the previous logic to wait better. Have you tried increasing `WAIT_AFTER_LAST_REQUEST` to 2 or 3 seconds to see if that helps?

**Comment by Woodya** [comment]
inre plugin, I think plugin flexibility is powerful & generally useful, but increases setup complexity. Which is why i presume you baked in blocked-url patterns rather than making that a plugin. It's your call, but we like to be able to control our system with a minimal amount of new plugins. It simply makes the base system a more compelling solution if it can handle the common cases. That said, I'm not sure if my use case is considered common, you probably have the best perspective on that from community of contributors. Though anyone using the system locally for client side mvc/escaped-fragment etc. should consider doing something like this if the phantom proxy option doesn't solve their needs. 

inre ```pendingRequests```, in our case, and in many angular or users of google maps etc. the page is not done loading at the point where javascript is executed. That logic does not apply to dynamic loaders, which are somewhat common i would expect in many of the primary use cases of prerender.
```WAIT_AFTER_LAST_REQUEST``` is just a hack that will make all requests take longer and still render too quickly in a variety of tail response time cases, and when an entire site is crawled, that's going to happen.

My follow up question would be: why would you set wait-after if you can simply know when there are no further resource requests? When you say 'change previous logic to wait better', which are of code are you referring to? I spent a bit of time looking around (but i'm new to this code). This change seemed the minimal manipulation to keep the service from rendering prematurely. I could see adding a config flag for this sort of thing, but basically if you render while there are still pending requests you're not pre-rendering the page as a browser would, you're serving the intermediate state, which in the case of some sites is a loading gif. For any page that doesn't generate additional resource requests there is no change, so it would seem to be the better alternative to await the requests being completed.

Also, I have a concern that pendingRequests == 0 is perhaps insufficient, as i'm not yet clear how the resource has been parsed/loaded completion is denoted, but this change eliminated 'loading state' renders when i tried it with a variety of sites.

**Comment by Woodya** [comment]
been reading more and attempting to understand how to implement this as a plugin and i'm coming up empty. are you contemplating something like:
```
server.onResourceRequested = function (requestData, request, blockedResources) {
        ...
        this._pluginEvent("onResourceRequested", [requestData, request, blockedResources], function() {});
};
```

**Comment by thoop** [comment]
Yes, that's how we'd do the plugin. We'd probably send the request and response as well so that people could do anything they need with the phantomjs page. We didn't do blocked resources that way since the blocked resources have to be serialized over to phantomjs' execution context.

Regarding pendingRequests, [this code](https://github.com/prerender/prerender/blob/master/lib/server.js#L270) checks pendingRequests <= 0 just before `evaluateJavascriptOnPage` so we should do any check there to make sure that pendingRequests is <= 0 before moving on. `WAIT_AFTER_LAST_REQUEST` actually does try to wait and if any requests are made within the wait window, it starts over.

Sorry for the unclear code :) The next major version will clean all of that up.

**Comment by thoop** [comment]
Sorry for the long delay here. Looks like you've added a lot more to this. We changed to a different phantomjs -> node bridge in our latest version (4.0.3) so the phantomjs API changed a bit. Let me know if you still think anything from this is important to merge back into master.

Thanks!

**Pull request closed without merging**
