### PR TITLE
Add a header to force update.

### PR DESCRIPTION
**Pull request by sunshineo**
I found this very useful to me.

### CODE REVIEW

**Comment by thoop** [comment]
Thanks! Did you try sending a `HEAD` request since we already have this?
```
if(req.method !== 'GET') {
  return next();
}
```
Since that works similarly.

**Comment by sunshineo** [comment]
@thoop Thank you very much! Let me look into this.

**Comment by sunshineo** [comment]
@thoop This could work. But my test did not go through. Because I'm using prerender-node, which do a GET even though I'm hitting with a HEAD. As we can see from this line
https://github.com/prerender/prerender-node/blob/master/index.js#L188 , it always do a GET. Search in that file for "req.method" and you will see it is not being used at all.

I'm going to file an issue on that project.

**Comment by sunshineo** [comment]
I have created an issue https://github.com/prerender/prerender-node/issues/120

**Pull request closed without merging**
