### PR TITLE
Fix for documents with no explicit html tag

### PR DESCRIPTION
**Pull request by brycekahle**

### CODE REVIEW

**Comment by thoop** [comment]
Thanks @brycekahle! Have you run into many websites where this is an issue? Wouldn't Chrome automatically add an <html> tag if one isn't present?

**Comment by brycekahle** [comment]
It might. This is what rendertron uses, and I saw a decent perf increase when using it.

**Comment by thoop** [comment]
Awesome. We'll run some tests and merge soon.

**Comment by thoop** [comment]
Thanks for the pull request!

**Comment by gelinger777** [comment]
i am not sure if this is related, but we just installed prerender from master branch and we are getting  following picture 

html<html lang="en-us"><head>



An "html" string is prepended to the content .... 

Can it be because of this merge?

**Comment by thoop** [comment]
@gelinger777 It looks like this was a change in Chrome v72 and we just pushed a fix: https://github.com/prerender/prerender/issues/563

**Pull request merged**
