### PR TITLE
Add download completion notification through window.prerenderDownloadComplete

### PR DESCRIPTION
**Pull request by frankiethekneeman**
I work at a media company using a self hosted fleet of prerender servers to keep our site crawlable by google.  One major frustration we've been having is that because of a host of resources placed on our page which are important for ad revenue but not important for SEO, the prerender download check always goes all the way to the timeout before moving on to the JS checking.  This leads to the server overshooting the `window.prerenderReady` boolean - often by long enough to do some pretty serious SEO damage to the page.  We'd appreciate the ability to notify prerender directly that the important resources have been downloaded, so that the server can move past the download waiting earlier.

We think that other sites might benefit from this ability, so I'm opening this MR to add that functionality.

To that effect, I've changed the downloadChecker logic from a `setInterval` to a recursive `setTimeout`, and used the `page.evaluate` functionality from phantomJS to ascertain the existence and value of a `window.prerenderDownloadComplete` variable.  By setting this to `true`, a site can notify the prerender server that the important resources have been downloaded and allow it to move on, ensuring that the page renders more predictably through prerender.

While I was editing the `server.checkIfPageIsDoneLoading` function, I took the liberty of cleaning up some of the check logic into more self-documenting variables, but I assure you the base functionality is unchanged, and sites using prerender are will not find themselves more error prone because of this feature.

I tested as much as I could on my local, but I had trouble Identifying any unit tests that could be use to more confidently declare this patch functional and backwards compatible.  We are dedicated to this functionality, however, and would like very much to see it included in prerender - it's a great codebase, and we're excited to help make it better.  Please let us know what we can do to make this work for you.

### CODE REVIEW

**Comment by frankiethekneeman** [comment]
@thoop Any more thoughts on this?

**Comment by thoop** [comment]
I'm really sorry that I've been slacking on all of the github issues and pull requests. I've been so busy lately with our hosted prerender.io service that I haven't been able to get to these improvements yet!

I'll carve some time out soon to go through it and let you know.

Thanks,

**Comment by frankiethekneeman** [comment]
@thoop Thanks!  I look forward to it.

**Comment by thoop** [comment]
Hi @frankiethekneeman . Sorry for the delay with this PR.

Upon looking into it further, it looks like your `window.prerenderDownloadComplete` is exactly the same as our `window.prerenderReady`. Is that true?

**Comment by frankiethekneeman** [comment]
@thoop Well, it's based on the prerenderReady functionality, and yes it works in basically the same way, but it solves a different problem.  Our site depends on a large number of external resources and API calls, most of which are not necessary for SEO (ads, largely).  The result of this is that `req.prerender.pendingRequests` would never be zero, and prerender would quietly hum until the timeout was reached, in many cases rendering for several seconds past the time at which the application set the `window.prerenderReady` flag.

After testing some implementations that terminated the download wait based on the window.prerenderReady flag, I noticed some continued issues in overshoot, which I assumed was due to the overhead of switching from the download wait loop into the javascript wait loop, so I figured it would be useful to have a second breakpoint in which the application could inform prerender that it was done downloading crucial information, and that prerender could go on to testing the javascript - this has the added benefit of making the timeouts less costly in the case of application error, as I envisioned `window.prerenderDownloadComplete` being set to true at the end of whatever minified JS file carried the bulk of the application information, so a JS error which prevented `window.prerenderReady` from being set would timeout at a more reasonable time.

So, I guess, yes - in that it functions the same way, and no - in that it functions at a different place in the execution.

**Comment by thoop** [comment]
Ah, I see.

Ok, I'll take some time to look into it. Thanks!

**Comment by frankiethekneeman** [comment]
@thoop I'm sorry, I was merging master into my branch to facilitate the auto-merge - seems git's got me again.  I'll open a new MR when I've fixed the problem.

**Pull request closed without merging**
