### PR TITLE
removeScriptTags - also remove preload / prefetch

### PR DESCRIPTION
**Pull request by Nadav42**
remove preload, prefetch, preconnect because html should already be rendered, also fixed missing global flag with the rel="import" regex

### CODE REVIEW

**Comment by thoop** [comment]
Ah this is great. Let us take a look and make sure this won't break anything before we merge!

**Comment by Palmik** [comment]
Consider also adding `modulepreload`.

**Comment by michalhudecek** [comment]
This would help us a lot with the performance! Check out this bandwidth chart:

- ON = prerendering on
- OFF = prerendering off
- ON with prefetch links removed

image

**Comment by contra** [comment]
@thoop Any testing we could do to help get this merged?

**Comment by varrocs** [comment]
Closing this pull request.
The patch has been applied to https://github.com/prerender/prerender/commit/bd72aff4b730393b5a9b7fee8925cd93db1a602a

**Comment by contra** [comment]
@varrocs Thanks! Any idea when we can expect a release including these changes?

**Pull request closed without merging**
