### PR TITLE
Block woff fonts and css [UPD: woff fonts only]

### PR DESCRIPTION
**Pull request by sharshenov**
These resources do not affect the page rendering.

### CODE REVIEW

**Comment by brenoc** [comment]
I think if you remove CSS, Google will consider it as cloaking. Not sure about fonts though.

> If you pre-render pages, make sure that the content served to Googlebot matches the user's experience, both how it looks and how it interacts. Serving Googlebot different content than a normal user would see is considered cloaking, and would be against our Webmaster Guidelines.
[Source](http://googlewebmastercentral.blogspot.com.br/2015/10/deprecating-our-ajax-crawling-scheme.html)

**Comment by sharshenov** [comment]
Css is not able to change markup. Links to css files are still on the same
place. With this PR css and woff fonts are not loaded during the js->html
render operation only
15 окт. 2015 г. 9:09 AM пользователь "Breno Calazans" <
notifications@github.com> написал:

**Comment by brenoc** [comment]
Oh, I see, that's great, it should be more performant, right?

**Comment by sharshenov** [comment]
Yes. Less requests - faster render
15 окт. 2015 г. 9:19 AM пользователь "Breno Calazans" <
notifications@github.com> написал:

**Comment by thoop** [comment]
I'd still worry about not loading css. css can cause layout changes and javascript might be used to detect layout changes. Unless there are some benchmarks showing that css causes pages to load much slower, I think it's just a hypothetical gain.

We've had some issues with us not loading images in phantomjs due to some websites waiting for layout changes due to images or onload functions.

**Comment by sharshenov** [comment]
Ok. I've updated PR to block .woff fonts only.

**Comment by MrAlexWeber** [comment]
Adding this small tweak reduced my load time by ~5s. Highly recommended for anyone reading this thread.

**Comment by thoop** [comment]
Awesome, sorry I haven't merged yet!

**Pull request merged**
