### PR TITLE
fix some encoding issues

### PR DESCRIPTION
**Pull request by truongsinh**
3 new test added, 1 test modified, tested against node v4.3.1

### CODE REVIEW

**Comment by thoop** [comment]
What are the issues you were seeing that caused you to fix this? Can you give more information on why this is needed?

I don't think the URL that you modified in the test is valid:

`http://www.example.com/?param3=yes&param4=no#!/user/1?param1=yes&param2=no`

And the tests that you added aren't URLs we'd ever expect to see sent to us.

**Comment by truongsinh** [comment]
> http://www.example.com/?param3=yes&param4=no#!/user/1?param1=yes&param2=no

Why not, why do you assume that, for example, an angular app cannot have such query params? Is it documented somewhere? Because the last time I checked https://developers.google.com/webmasters/ajax-crawling/docs/specification#basic-definitions, it has:

> - Pretty URL: Any URL containing a hash fragment beginning with !, for example, `www.example.com?myquery#!key1=value1&key2=value2`
- Ugly URL: Any URL containing a query parameter with the key _escaped_fragment_, for example, `www.example.com?myquery&_escaped_fragment_=key1=value1%26key2=value2. `

Besides, here's the screenshot from real application, which I believe does not violate any industry standard:
screen shot 2016-04-26 at 06 59 58

> And the tests that you added aren't URLs we'd ever expect to see sent to us.

Again, why not? Why `http://www.example.com/productNumber=123%23456?_escaped_fragment_=/user/` is not a valid case, but `http://www.example.com/productNumber=123%23456?_escaped_fragment_=` and `http://www.example.com/productNumber=123%23456?_escaped_fragment_=/user/` is?

Besides, I haven't run any benchmark, but I have a strong opinion that it is more performant. In addition to that, I just remove bunch of unnecessary encoding and decoding, make the code cleaner.

**Comment by thoop** [comment]
> http://www.example.com/?param3=yes&param4=no#!/user/1?param1=yes&param2=no

You have two different query string parameters there, which is an invalid URL.

> http://www.example.com/productNumber=123%23!456?_escaped_fragment_=

A `#!` should never be encoded in the URL like that. The `#!` will be transformed into the `_escaped_fragment_` query parameter.

And you removed the code that we use to decode incoming requests (which it looks like we need a test for since removing that didn't break a test). The first decode is necessary since the entire URL string can be encoded when coming into the Prerender server, which is why we decode and then correctly encode the hash. The second decode is necessary because `url.format` encodes some characters but not all.

I appreciate the pull request, but we need to keep that decoding section in there.

**Comment by truongsinh** [comment]
> You have two different query string parameters there, which is an invalid URL.

That's true, we have 2 different query string, the first is for backend (to make database filter/index), and the second is query string for the SPA frontend itself (for example, frontend filter https://docs.angularjs.org/api/ng/filter/filter), and as explained, I already gave you the real-life example, as well as document from Google themselves

> www.example.com?myquery#!key1=value1&key2=value2

My question is that whether there are any documents saying that query string for SPA is illegitimate. If there are, we can admit we have violated industry standard and will fix our app to make sure it follows. If there is none, you can even create one yourself, state clearly what to do and what not to do, then we can either agree and follow that, or just disagree and make a fork and use our own. 

> A #! should never be encoded in the URL like that. The #! will be transformed into the _escaped_fragment_ query parameter.

We're not trying to encode "#!" into "_escaped_fragment_ query". What we mean is we have a product slug "123#!456", with URL http://www.example.com/?productSlug=123%23!456 and product "123abc456" with URL http://www.example.com/?productSlug=123abc456. As the previous point, if there is any document prohibiting us from using "#!" in ID/slug/filter/whatever sits in query param, please either have it referenced, or just create a document saying "Sorry, you MUST NOT have `#!` in any of your query string value, if you do, please update your database"

**Comment by thoop** [comment]
If you look at the URL from Google, they don't have two query strings.

> www.example.com?myquery#!key1=value1&key2=value2

They have one `?` and then some key=values after the #!. So the double query string is not in there.

As for the `#!` in the URL, that's interesting. Due to the specific nature of the `#!` meaning something important for the crawlers, I would suggest that you make sure you don't have a `#!` in your URLs. I don't think that's invalid at all but you'd have a high chance of crawlers getting confused with those URLs and getting unexpected results.

**Pull request closed without merging**
