### PR TITLE
Add function to perform a graceful browser restart

### PR DESCRIPTION
**Pull request by brycekahle**

### CODE REVIEW

**Comment by brycekahle** [comment]
I did mean to sent it to the netlify version. I needed a way to manually initiate a graceful restart, rather than wait for the time-based way.

**Comment by thoop** [comment]
Ah, interesting. Are you running into issues that we might be able to look into preventing?

**Comment by brycekahle** [comment]
Nothing the fault of this library. We just need a release valve in case Chrome starts using too much system memory. This graceful restart is better than restarting the entire service, since it is easier to prevent requests from getting lost.

**Comment by thoop** [comment]
Yep, totally agree. Just curious!

**Pull request closed without merging**
