### PR TITLE
2 new plugins `base href` and `inline css`

### PR DESCRIPTION
**Pull request by truongsinh**
use plugin `base href` and `inline css` so that page can be display without additional proxied resources like images (which are served directly from original host, thanks to `<base href=`) or stylesheets (which are inlined). Caveat: font

### CODE REVIEW

**Comment by thoop** [comment]
Thanks! Ideally, you wouldn't need this since you should always be serving the prerendered pages from your domain so all proxied resources should work correctly. Would this just be cosmetic so you could view it from somewhere else?

**Comment by truongsinh** [comment]
> Would this just be cosmetic so you could view it from somewhere else?

Exactly, our use case is to proxy our clients' pages with their permission, some of which are served HTTP, while our site is always served with HTTPS, causing conflicts with stylesheets and fonts.

**Comment by thoop** [comment]
I'd like to have a small amount of plugins in the actual Prerender repo so we don't have to bump our version or deploy new versions for just changes to plugins. You can host your plugins on github and other people can still pull them in and use them on their Prerender server. I think that would be ideal here since your use case is not a common one. I wouldn't want people to be confused and think that your plugins are required if they were included in our repo.

**Comment by truongsinh** [comment]
> You can host your plugins on github and other people can still pull them in and use them on their Prerender server.

Fair enough, but then we don't yet have proper mechanism and document for that.

**Comment by thoop** [comment]
It's just the standard node process of including and using other modules.

see: https://github.com/lammertw/prerender-mongodb-cache

**Comment by truongsinh** [comment]
Feedback resolved (in a rush) manner. I'd appreciate if you can mention it some where in readme or example

**Comment by thoop** [comment]
Sure! Just put the information that you added, commented out, in your readme for your repo so that people know how to install and use your plugin if they want. Just like the mongo one.

**Pull request closed without merging**
