### PR TITLE
Add license to package.json

### PR DESCRIPTION
**Pull request by taylorkearns**
Add the MIT license info ("AML") to the package.json file.

### CODE REVIEW

**Comment by thoop** [comment]
What is "AML"? Shouldn't it be mit?

**Comment by taylorkearns** [comment]
I believe we're supposed to use the SPDX identifier for the license? I was surprised too, maybe I'm reading things incorrectly. Check out https://docs.npmjs.com/files/package.json and https://spdx.org/licenses/.

**Comment by thoop** [comment]
Looks like AML is the "Apple MIT License" where they have a regular MIT license down the list and the abbreviation is just "MIT"

**Comment by taylorkearns** [comment]
You're right, my mistake sorry. I'll update the PR in case you still want to use it.

**Comment by thoop** [comment]
Thanks!

**Pull request merged**
